ALTER TABLE assets ADD COLUMN paypal_enabled BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE assets ADD COLUMN price_usd DOUBLE PRECISION;
ALTER TABLE assets ADD COLUMN paypal_env_key VARCHAR(255);

ALTER TABLE orders ADD COLUMN payment_method VARCHAR(50) DEFAULT 'ROBUX' NOT NULL;
ALTER TABLE orders ADD COLUMN purchase_price_usd DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN paypal_order_id VARCHAR(255);

ALTER TABLE transactions ADD COLUMN currency VARCHAR(10) DEFAULT 'ROBUX' NOT NULL;
ALTER TABLE transactions ADD COLUMN amount_usd DOUBLE PRECISION;