name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull changes and run deploy script
        run: |
          cd ~/myapps/warware/backend
          git pull
          chmod +x deploy.sh
          ./deploy.sh